# Theme
include ./current-theme.conf
#font_family      Fira Code Regular
#bold_font        Fira Code bold
#italic_font      auto
#bold_italic_font auto
#
font_family          Maple Mono NF Regular
bold_font            Maple Mono NF Bold
italic_font          Maple Mono NF Italic
bold_italic_font     Maple Mono NF Bold Italic
font_features        MapleMonoNF-regular  +ss04 +ss05 +zero +ss06 +cv35 +ss08 +cv61
font_features        maplemonoNF-bold  +ss04 +ss05 +zero +ss06 +cv35 +ss08 +cv61
font_features        maplemonoNF-italic  +ss04 +ss05 +zero +ss06 +cv35 +ss08 +cv61
font_features        maplemonoNF-bolditalic  +ss04 +ss05 +zero +ss06 +cv35 +ss08 +cv61
#font_features        FiraCode-Regular +cv01 +cv31 +cv30 +ss04 +cv04
#font_features        FiraCode-bold +cv01 +cv31 +cv30 +ss04 +cv04
#font_features        FiraCode-Italic +cv01 +cv31 +cv30 +ss04 +cv04
underline_exclusion 1
modify_font underline_position 1
#symbol_map U+25EF Fira Code U+0028,U+0029,U+002C,U+002E,U+003A,U+003B,U+201C,U+201D,
#symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font 
font_size 18
cursor_blink_interval 0
detect_urls yes
mouse_hide_wait 5
disable_ligatures cursor
cursor_trail 20
cursor_trail_decay 0.0 0.3
cursor_trail_start_threshold 10
background_opacity 0.95
paste_actions quote-urls-at-prompt,confirm

enable_csi_u_key_encoding yes
