[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
[[mgr.prepend_keymap]]
on  = ["f","f"] 
run = "plugin fzf"
[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"

[[mgr.prepend_keymap]]
on   = [ "G" ]
run  = "plugin lazygit"
desc = "run lazygit"
